name: ripple-server
version: 0.0.0.0

extra-source-files:
- openapi.json

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - aeson
  - autodocodec-openapi3
  - autodocodec
  - bytestring
  - deepseq
  - genvalidity
  - hashable
  - monad-logger
  - mtl
  - openapi3
  - path-pieces
  - persistent
  - persistent-sqlite
  - persistent-template
  - servant
  - servant-client
  - servant-multipart
  - servant-multipart-client
  - servant-server
  - text
  - validity
  - wai
  - wai-extra
  - warp

executables:
  ripple-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ripple-server

tests:
  ripple-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autodocodec-openapi3
    - bytestring
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-persistent
    - http-media
    - insert-ordered-containers
    - lens
    - openapi3
    - path-pieces
    - ripple-server
    - servant
    - servant-client
    - servant-multipart
    - servant-openapi3
    - sydtest
    - sydtest-aeson
    - text
